Update dependencies and drop support for Python 3.6 and Python 3.7
google/openhtf pull request #1018
Opened 2022-08-15 20:18 UTC by jonasclaes

This PR contains updated dependency constraints. It also drops support for Python 3.6 and Python 3.7, due to these changes. I think it is about time that we drop these versions since they are quite old already.
We're talking 4 years old for the release date of Python 3.7.

2022-08-15 20:20 UTC, jonasclaes commented
Tests have passed using the Tox runner.

2022-08-25 11:45 UTC, jonasclaes commented
I would like to bump this PR again.

2022-09-08 21:48 UTC, dbhatman commented
Please also update the python version matrix in .github/build_and_deploy.yml!

2022-09-08 21:56 UTC, cricdecyan requested changes

2022-09-08 21:56 UTC, cricdecyan commented on tox.ini
> -envlist = py36,py37,py39
Let's keep Py3.7 for now.

2022-09-09 10:36 UTC, closed without merging

2022-09-09 11:08 UTC, jonasclaes commented
A new PR has been created. #1027